services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      proshop-network:
        aliases:
          - mongo

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/proshop
    networks:
      proshop-network:
        aliases:
          - backend
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:80'
    networks:
      proshop-network:
        aliases:
          - frontend
    depends_on:
      - backend

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile.prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    networks:
      proshop-network:
        aliases:
          - prometheus

networks:
  proshop-network:
    driver: bridge
